# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DESCRIPTION="Default linker configuration for clang"
HOMEPAGE="https://clang.llvm.org/"
S=${WORKDIR}

LICENSE="public-domain"
SLOT="${PV}"
KEYWORDS="amd64 arm arm64 ~loong ~mips ppc ppc64 ~riscv ~sparc x86 ~arm64-macos ~x64-macos"
IUSE="default-lld default-mold lto"

RDEPEND="
	default-lld? ( >=llvm-core/lld-${PV} )
	!default-lld? (
		default-mold? ( sys-devel/mold )
		!default-mold? ( sys-devel/binutils )
		lto? ( >=llvm-core/llvm-${PV} )
	)
"

src_install() {
	insinto "/etc/clang/${SLOT}"
	newins - gentoo-linker.cfg <<-EOF
		# This file is initially generated by ${CATEGORY}/${PN}.
		# It is used to control the default linker used by clang.

	EOF
	if use default-lld; then
		newins - gentoo-linker.cfg <<-EOF
			-fuse-ld=lld
		EOF
	elif use default-mold; then
		newins - gentoo-linker.cfg <<-EOF
			-fuse-ld=mold
		EOF
	else
		newins - gentoo-linker.cfg <<-EOF
			-fuse-ld=bfd
		EOF
	fi
}
